version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: logic
      POSTGRES_USER: logic
      POSTGRES_PASSWORD: logic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: